# Generated by Django 6.0.1 on 2026-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Punten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummerSpeler', models.IntegerField()),
                ('punten', models.IntegerField()),
                ('matchCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=25)),
                ('voornaam', models.CharField(max_length=25)),
                ('email', models.EmailField(default='no@email.be', max_length=50)),
            ],
        ),
    ]
